//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerceProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int id_produit { get; set; }
        public string reference { get; set; }
        public Nullable<double> prix { get; set; }
    }
}
