// <auto-generated />
namespace ECommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class somechangess : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(somechangess));
        
        string IMigrationMetadata.Id
        {
            get { return "202108240940321_somechangess"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
